// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: scan/v1/scan.proto

package scanv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScanPlugin_Capability_FullMethodName    = "/scan.v1.ScanPlugin/Capability"
	ScanPlugin_Execute_FullMethodName       = "/scan.v1.ScanPlugin/Execute"
	ScanPlugin_ExecuteStream_FullMethodName = "/scan.v1.ScanPlugin/ExecuteStream"
	ScanPlugin_Prepare_FullMethodName       = "/scan.v1.ScanPlugin/Prepare"
)

// ScanPluginClient is the client API for ScanPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ScanPlugin is the generic contract every scanner tool plugin implements. It
// mirrors the host-side scan.Executor port: Capability advertises the tool's
// capability string, ExecuteStream runs one scan with structured progress, and Prepare is a pre-scan hook
// (a no-op for every tool except nuclei, which uses it to sync templates).
//
// Tool-specific result payloads never appear in this contract: Execute returns
// the result as opaque JSON bytes (raw_json) so the host decodes it into the
// same map[string]any it persists as JSONB today, keeping the result processor
// unchanged.
type ScanPluginClient interface {
	Capability(ctx context.Context, in *CapabilityRequest, opts ...grpc.CallOption) (*CapabilityResponse, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	ExecuteStream(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteEvent], error)
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error)
}

type scanPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewScanPluginClient(cc grpc.ClientConnInterface) ScanPluginClient {
	return &scanPluginClient{cc}
}

func (c *scanPluginClient) Capability(ctx context.Context, in *CapabilityRequest, opts ...grpc.CallOption) (*CapabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilityResponse)
	err := c.cc.Invoke(ctx, ScanPlugin_Capability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scanPluginClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, ScanPlugin_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scanPluginClient) ExecuteStream(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ScanPlugin_ServiceDesc.Streams[0], ScanPlugin_ExecuteStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteRequest, ExecuteEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScanPlugin_ExecuteStreamClient = grpc.ServerStreamingClient[ExecuteEvent]

func (c *scanPluginClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareResponse)
	err := c.cc.Invoke(ctx, ScanPlugin_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScanPluginServer is the server API for ScanPlugin service.
// All implementations must embed UnimplementedScanPluginServer
// for forward compatibility.
//
// ScanPlugin is the generic contract every scanner tool plugin implements. It
// mirrors the host-side scan.Executor port: Capability advertises the tool's
// capability string, ExecuteStream runs one scan with structured progress, and Prepare is a pre-scan hook
// (a no-op for every tool except nuclei, which uses it to sync templates).
//
// Tool-specific result payloads never appear in this contract: Execute returns
// the result as opaque JSON bytes (raw_json) so the host decodes it into the
// same map[string]any it persists as JSONB today, keeping the result processor
// unchanged.
type ScanPluginServer interface {
	Capability(context.Context, *CapabilityRequest) (*CapabilityResponse, error)
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	ExecuteStream(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteEvent]) error
	Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error)
	mustEmbedUnimplementedScanPluginServer()
}

// UnimplementedScanPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScanPluginServer struct{}

func (UnimplementedScanPluginServer) Capability(context.Context, *CapabilityRequest) (*CapabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capability not implemented")
}
func (UnimplementedScanPluginServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedScanPluginServer) ExecuteStream(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteEvent]) error {
	return status.Error(codes.Unimplemented, "method ExecuteStream not implemented")
}
func (UnimplementedScanPluginServer) Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedScanPluginServer) mustEmbedUnimplementedScanPluginServer() {}
func (UnimplementedScanPluginServer) testEmbeddedByValue()                    {}

// UnsafeScanPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScanPluginServer will
// result in compilation errors.
type UnsafeScanPluginServer interface {
	mustEmbedUnimplementedScanPluginServer()
}

func RegisterScanPluginServer(s grpc.ServiceRegistrar, srv ScanPluginServer) {
	// If the following call panics, it indicates UnimplementedScanPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScanPlugin_ServiceDesc, srv)
}

func _ScanPlugin_Capability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanPluginServer).Capability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScanPlugin_Capability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanPluginServer).Capability(ctx, req.(*CapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScanPlugin_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanPluginServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScanPlugin_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanPluginServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScanPlugin_ExecuteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ScanPluginServer).ExecuteStream(m, &grpc.GenericServerStream[ExecuteRequest, ExecuteEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScanPlugin_ExecuteStreamServer = grpc.ServerStreamingServer[ExecuteEvent]

func _ScanPlugin_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanPluginServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScanPlugin_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanPluginServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScanPlugin_ServiceDesc is the grpc.ServiceDesc for ScanPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScanPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scan.v1.ScanPlugin",
	HandlerType: (*ScanPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Capability",
			Handler:    _ScanPlugin_Capability_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _ScanPlugin_Execute_Handler,
		},
		{
			MethodName: "Prepare",
			Handler:    _ScanPlugin_Prepare_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteStream",
			Handler:       _ScanPlugin_ExecuteStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "scan/v1/scan.proto",
}
