// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: scan/v1/scan.proto

package scanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CapabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityRequest) Reset() {
	*x = CapabilityRequest{}
	mi := &file_scan_v1_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityRequest) ProtoMessage() {}

func (x *CapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan_v1_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityRequest.ProtoReflect.Descriptor instead.
func (*CapabilityRequest) Descriptor() ([]byte, []int) {
	return file_scan_v1_scan_proto_rawDescGZIP(), []int{0}
}

type CapabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityResponse) Reset() {
	*x = CapabilityResponse{}
	mi := &file_scan_v1_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityResponse) ProtoMessage() {}

func (x *CapabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scan_v1_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityResponse.ProtoReflect.Descriptor instead.
func (*CapabilityResponse) Descriptor() ([]byte, []int) {
	return file_scan_v1_scan_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilityResponse) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_scan_v1_scan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan_v1_scan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_scan_v1_scan_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ExecuteRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type ExecuteResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Capability string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	// raw_json is json.Marshal of the tool's ScanResult.Raw payload.
	RawJson            []byte `protobuf:"bytes,2,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	StartedAtUnixNano  int64  `protobuf:"varint,3,opt,name=started_at_unix_nano,json=startedAtUnixNano,proto3" json:"started_at_unix_nano,omitempty"`
	FinishedAtUnixNano int64  `protobuf:"varint,4,opt,name=finished_at_unix_nano,json=finishedAtUnixNano,proto3" json:"finished_at_unix_nano,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_scan_v1_scan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scan_v1_scan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_scan_v1_scan_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *ExecuteResponse) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

func (x *ExecuteResponse) GetStartedAtUnixNano() int64 {
	if x != nil {
		return x.StartedAtUnixNano
	}
	return 0
}

func (x *ExecuteResponse) GetFinishedAtUnixNano() int64 {
	if x != nil {
		return x.FinishedAtUnixNano
	}
	return 0
}

// PrepareRequest carries the control-plane-issued node JWT so a plugin that
// needs to fetch remote state (nuclei: the template bundle) can authenticate.
// The token is read fresh at call time on the host side, so it can't be a
// static env var.
type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_scan_v1_scan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan_v1_scan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_scan_v1_scan_proto_rawDescGZIP(), []int{4}
}

func (x *PrepareRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type PrepareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	mi := &file_scan_v1_scan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scan_v1_scan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_scan_v1_scan_proto_rawDescGZIP(), []int{5}
}

var File_scan_v1_scan_proto protoreflect.FileDescriptor

const file_scan_v1_scan_proto_rawDesc = "" +
	"\n" +
	"\x12scan/v1/scan.proto\x12\ascan.v1\"\x13\n" +
	"\x11CapabilityRequest\"4\n" +
	"\x12CapabilityResponse\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\"\x9c\x01\n" +
	"\x0eExecuteRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12;\n" +
	"\x06params\x18\x02 \x03(\v2#.scan.v1.ExecuteRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\x01\n" +
	"\x0fExecuteResponse\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x19\n" +
	"\braw_json\x18\x02 \x01(\fR\arawJson\x12/\n" +
	"\x14started_at_unix_nano\x18\x03 \x01(\x03R\x11startedAtUnixNano\x121\n" +
	"\x15finished_at_unix_nano\x18\x04 \x01(\x03R\x12finishedAtUnixNano\"/\n" +
	"\x0ePrepareRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\"\x11\n" +
	"\x0fPrepareResponse2\xcf\x01\n" +
	"\n" +
	"ScanPlugin\x12E\n" +
	"\n" +
	"Capability\x12\x1a.scan.v1.CapabilityRequest\x1a\x1b.scan.v1.CapabilityResponse\x12<\n" +
	"\aExecute\x12\x17.scan.v1.ExecuteRequest\x1a\x18.scan.v1.ExecuteResponse\x12<\n" +
	"\aPrepare\x12\x17.scan.v1.PrepareRequest\x1a\x18.scan.v1.PrepareResponseBAZ?github.com/trganda/vpt-scanner-plugins/sdk/proto/scan/v1;scanv1b\x06proto3"

var (
	file_scan_v1_scan_proto_rawDescOnce sync.Once
	file_scan_v1_scan_proto_rawDescData []byte
)

func file_scan_v1_scan_proto_rawDescGZIP() []byte {
	file_scan_v1_scan_proto_rawDescOnce.Do(func() {
		file_scan_v1_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scan_v1_scan_proto_rawDesc), len(file_scan_v1_scan_proto_rawDesc)))
	})
	return file_scan_v1_scan_proto_rawDescData
}

var file_scan_v1_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_scan_v1_scan_proto_goTypes = []any{
	(*CapabilityRequest)(nil),  // 0: scan.v1.CapabilityRequest
	(*CapabilityResponse)(nil), // 1: scan.v1.CapabilityResponse
	(*ExecuteRequest)(nil),     // 2: scan.v1.ExecuteRequest
	(*ExecuteResponse)(nil),    // 3: scan.v1.ExecuteResponse
	(*PrepareRequest)(nil),     // 4: scan.v1.PrepareRequest
	(*PrepareResponse)(nil),    // 5: scan.v1.PrepareResponse
	nil,                        // 6: scan.v1.ExecuteRequest.ParamsEntry
}
var file_scan_v1_scan_proto_depIdxs = []int32{
	6, // 0: scan.v1.ExecuteRequest.params:type_name -> scan.v1.ExecuteRequest.ParamsEntry
	0, // 1: scan.v1.ScanPlugin.Capability:input_type -> scan.v1.CapabilityRequest
	2, // 2: scan.v1.ScanPlugin.Execute:input_type -> scan.v1.ExecuteRequest
	4, // 3: scan.v1.ScanPlugin.Prepare:input_type -> scan.v1.PrepareRequest
	1, // 4: scan.v1.ScanPlugin.Capability:output_type -> scan.v1.CapabilityResponse
	3, // 5: scan.v1.ScanPlugin.Execute:output_type -> scan.v1.ExecuteResponse
	5, // 6: scan.v1.ScanPlugin.Prepare:output_type -> scan.v1.PrepareResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scan_v1_scan_proto_init() }
func file_scan_v1_scan_proto_init() {
	if File_scan_v1_scan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scan_v1_scan_proto_rawDesc), len(file_scan_v1_scan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scan_v1_scan_proto_goTypes,
		DependencyIndexes: file_scan_v1_scan_proto_depIdxs,
		MessageInfos:      file_scan_v1_scan_proto_msgTypes,
	}.Build()
	File_scan_v1_scan_proto = out.File
	file_scan_v1_scan_proto_goTypes = nil
	file_scan_v1_scan_proto_depIdxs = nil
}
